const PENDING_REVIEW = "PENDING_REVIEW";
const PUBLISHED = "PUBLISHED";
const REFUSED = "REFUSED";
const DRAFT = "DRAFT";
const OVER_ROOM = "OVER_ROOM";
const DELETED = "DELETED";

export const PostStatus =  {
    PENDING_REVIEW,
    PUBLISHED,
    REFUSED,
    DRAFT,
    OVER_ROOM,
    DELETED
}