const GlobalActions = {
    CHANGE_USER: "CHANGE_USER",
    SET_USER_INFO: "SET_USER_INFO",
    SET_USERS: "SET_USERS",
    CHANGE_POST: "CHANGE_POST",
    SET_POST_INFO: "SET_POST_INFO",
    SET_POSTS: "SET_POSTS",
    CHANGE_UTILITY: "CHANGE_UTILITY",
    CHANGE_CATEGORY: "CHANGE_CATEGORY",
    SET_PAGE_TYPE: "SET_PAGE_TYPE",
    SEARCH: "SEARCH",
    END_SEARCH: "END_SEARCH",
    HIDE_SEARCH: "HIDE_SEARCH",
    CLEAR_SEARCH: "CLEAR_SEARCH",
    RELOAD_PAGE: "RELOAD_PAGE",
    LOGGED_IN: "LOGGED_IN",
    LOGGED_OUT: "LOGGED_OUT",
}
export {GlobalActions}